FEATURE: Collapsable sidebar
paviliondev/layouts-category-list-widget pull request #3
Opened 2021-07-28 22:43 UTC by keegangeorge

Adds support for default category logos when logos are not present. Also adds the ability to toggle to collapse/expand sidebar to show icons only or full widget.

2021-08-02 11:18 UTC, angusmcleod requested changes

2021-08-02 11:18 UTC, angusmcleod commented on common/common.scss
> +    .minimize-icon {
Missing a line here (before child rule)

2021-08-02 11:18 UTC, angusmcleod commented on javascripts/discourse/widgets/layouts-category-list.js
> +  html(attrs, state) {
Considering we're always going to have the same result here, we should perhaps simplify this a bit, i.e.

```
html() {
   return [
      h('div.category-logo.minimize-icon', iconNode('chevron-circle-left')),
      h('div.category-name.minimize-text', I18n.t(themePrefix("minimize_button_label")))
   ]
}
```

We can always add in more logic later, however if you look at the code now you're first given the impression there must be some other logic there, but it turns out it's always the same two elements.

2021-08-02 11:18 UTC, angusmcleod commented on javascripts/discourse/widgets/layouts-category-list.js
> +      categoryDetails.forEach((category) => {
@keegangeorge Like with jquery we should only be using javascript to change the classList outside of the render thread of the frameworks we're using if it's the last option available. Rather we should be using:

1. Events to send actions up the widget hierarchy
2. Attributes to send values and current state down the widget hiearchy

Then updating the classlists of various widgets or their html using ``attrs`` and ``state``. Only if that's not possible do we resort to updating the DOM directly like this. Same in Ember as well. Try to use the framework first and direct class manipulation like this as a last resort.

If you're not sure what I'm talking about here, let's chat about it in our catchup this week.

2021-08-09 16:59 UTC, keegangeorge commented
Improved and moved some functionality directly to layouts plugin so it can be used by other widgets as well.
See PR: https://github.com/paviliondev/discourse-layouts/pull/16

2021-08-12 21:32 UTC, merged